import { FormEvent, useEffect, useState } from 'react'
import { API_BASE, api } from '../lib/api'
import { useRecognition } from '../hooks/useRecognition'
import { CameraStage } from '../components/CameraStage'

export function Collector(){const [label,setLabel]=useState('help');const [signer,setSigner]=useState('signer-01');const [consent,setConsent]=useState(false);const [collectorId,setCollectorId]=useState<string|null>(null);const [result,setResult]=useState<any>(null);const r=useRecognition('general',collectorId)
 const [clipPhrase,setClipPhrase]=useState('');const [clipFile,setClipFile]=useState<File|null>(null);const [clipVerified,setClipVerified]=useState(false);const [clipStatus,setClipStatus]=useState('')
 useEffect(()=>{if(collectorId && !r.running){void r.start()}},[collectorId])
 const start=async(e:FormEvent)=>{e.preventDefault();const x=await api<any>('/api/collector/start',{method:'POST',body:JSON.stringify({label,signer_id:signer,consent,save_raw_video:false})});setCollectorId(x.collector_id)}
 const stop=async()=>{r.stop();if(!collectorId)return;try{setResult(await api('/api/collector/stop',{method:'POST',body:JSON.stringify({collector_id:collectorId})}))}catch(e){setResult({error:String(e)})}finally{setCollectorId(null)}}
 const uploadClip=async(e:FormEvent)=>{e.preventDefault();if(!clipFile||!clipPhrase.trim())return;const form=new FormData();form.append('phrase',clipPhrase);form.append('source','team-recorded');form.append('license_note','Consented local recording');form.append('verified',String(clipVerified));form.append('file',clipFile);const res=await fetch(`${API_BASE}/api/sign-clips/register`,{method:'POST',body:form});setClipStatus(res.ok?'Clip saved locally':await res.text())}
 return <div className="content-page"><div className="page-title"><span className="eyebrow">DEVELOPER MODE</span><h1>Consented landmark collector</h1><p>Stores normalized landmark sequences only. Raw video is disabled.</p></div><section className="panel wide"><form className="collector-form" onSubmit={start}><label>Label<input value={label} onChange={e=>setLabel(e.target.value)} pattern="[a-z0-9_-]+"/></label><label>Signer ID<input value={signer} onChange={e=>setSigner(e.target.value)}/></label><label className="toggle"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I have explicit consent to collect this landmark sample.</label>{!collectorId?<button className="primary" disabled={!consent}>Begin take</button>:<button type="button" className="danger" onClick={stop}>Stop & save take</button>}</form></section>{collectorId&&<CameraStage {...r}/>} {result&&<pre className="panel codebox">{JSON.stringify(result,null,2)}</pre>}<section className="panel wide"><div className="panel-head"><div><span className="eyebrow">REVERSE ISL ASSET LAB</span><h2>Add a verified phrase clip</h2></div></div><p>Upload only a consented team/community recording whose ISL meaning has been checked. Unverified uploads are stored but never used as verified output.</p><form className="collector-form" onSubmit={uploadClip}><label>Phrase<input value={clipPhrase} onChange={e=>setClipPhrase(e.target.value)} placeholder="e.g. I need a doctor"/></label><label>Video clip<input type="file" accept="video/webm,video/mp4" onChange={e=>setClipFile(e.target.files?.[0]||null)}/></label><label className="toggle"><input type="checkbox" checked={clipVerified} onChange={e=>setClipVerified(e.target.checked)}/> ISL form/meaning has been verified by our team/reviewer.</label><button className="primary" disabled={!clipFile||!clipPhrase.trim()}>Store clip</button></form>{clipStatus&&<div className="notice">{clipStatus}</div>}</section></div>}
